import { tryRefreshAdminSession } from "@/lib/auth-api"
import {
  clearStoredAdminSession,
  emitAdminSessionExpired,
  loadStoredAccessToken,
  updateStoredAccessToken,
} from "@/lib/auth-storage"

export type PlannerTaskDomain =
  | "kanji"
  | "vocabulary"
  | "grammar"
  | "immersion"
  | "general"

export type PlannerTaskPriority = "high" | "medium" | "low"

export type PlannerCategory =
  | "KANJI"
  | "VOCABULARY"
  | "GRAMMAR"
  | "CHUNK"
  | "READING"
  | "IMMERSION"
  | "ACTIVE_STUDY"
  | "PASSIVE_STUDY"
  | "REVIEW"
  | "GENERAL"
  | "OTHER"

export type PlannerTaskPriorityEnum = "LOW" | "MEDIUM" | "HIGH"
export type PlannerTaskStatus = "PENDING" | "COMPLETED"

export type PlannerGoalCategory =
  | "IMMERSION"
  | "KANJI"
  | "VOCABULARY"
  | "GRAMMAR"
  | "GENERAL_REVIEW"
  | "READING"
  | "ACTIVE_STUDY"
  | "PASSIVE_STUDY"

export type WeeklyPlanStatus = "ACTIVE" | "COMPLETED" | "ARCHIVED"

export interface WeeklyGoalItemDto {
  category: PlannerGoalCategory
  targetValue: number
  unit?: string
}

export interface WeeklyGoalResponseDto {
  id: string
  category: PlannerGoalCategory
  name: string
  kanjiGlyph: string
  targetValue: number
  currentValue: number
  percentage: number
  unit: string
}

export interface WeeklyPlanResponseDto {
  id: string
  userId: string
  year: number
  weekNumber: number
  startDate: string
  endDate: string
  status: WeeklyPlanStatus
  notes: string | null
  goals: WeeklyGoalResponseDto[]
  createdAt: string
  updatedAt: string
}

export interface PlannerTaskDto {
  id: string
  domain: PlannerTaskDomain
  task: string
  description: string | null
  priority: PlannerTaskPriority
  estimatedMinutes: number
  kanjiGlyph: string
  dueAt: string
  status?: string
  completed?: boolean
  action:
    | { type: "review_kanji"; count: number }
    | { type: "review_vocabulary"; count: number }
    | { type: "study_grammar"; count: number }
    | { type: "immersion"; targetMinutes: number; loggedMinutes: number }
    | { type: "daily_review"; targetCount: number; completedCount: number }
    | { type: "general"; note: string }
}

export interface CreatePlannerTaskDto {
  title: string
  description?: string
  category?: PlannerCategory
  date: string
  scheduledTime?: string
  estimatedMinutes?: number
  priority?: PlannerTaskPriorityEnum
}

export interface UpdatePlannerTaskDto {
  title?: string
  description?: string
  category?: PlannerCategory
  date?: string
  scheduledTime?: string
  estimatedMinutes?: number
  actualMinutes?: number
  priority?: PlannerTaskPriorityEnum
  status?: PlannerTaskStatus
}

export interface TogglePlannerTaskDto {
  completed?: boolean
  actualMinutes?: number
}

export interface PlannerTaskItemResponseDto {
  id: string
  userId: string
  weeklyPlanId: string | null
  title: string
  description: string | null
  category: PlannerCategory
  categoryLabel: string
  kanjiGlyph: string
  date: string
  scheduledTime: string | null
  estimatedMinutes: number
  actualMinutes: number | null
  priority: PlannerTaskPriorityEnum
  status: PlannerTaskStatus
  completedAt: string | null
  isAutoGenerated: boolean
  actionPayload?: Record<string, unknown> | null
  createdAt: string
  updatedAt: string
}

export interface PlannerHabitDto {
  id: string
  name: string
  kanji: string
  domain: PlannerTaskDomain
  streak: number
  completedThisWeek: boolean[]
  weeklyTarget: number
}

export interface PlannerWeekDayDto {
  date: number
  day: string
  isToday: boolean
}

export interface PlannerWeeklyGoalDto {
  name: string
  kanji: string
  current: number
  target: number
  unit: string
}

export interface PlannerSummaryDto {
  tasksCompletedToday: number
  tasksPendingToday: number
  tasksTotalToday: number
  completionPercentage: number
  studyMinutesToday: number
  categoriesStudiedToday: string[]
  currentStreakDays: number
  longestStreakDays: number
  todayDateLabel: string
}

export interface PlannerOverviewResponseDto {
  week: PlannerWeekDayDto[]
  habits: PlannerHabitDto[]
  todayTasks: PlannerTaskDto[]
  weeklyGoals: PlannerWeeklyGoalDto[]
  summary: PlannerSummaryDto
}

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001"

async function requestJson<T>(
  path: string,
  options: RequestInit = {},
  includeAuthToken = false,
): Promise<T> {
  let shouldExpireSession = false

  const createHeaders = (token?: string | null): Headers => {
    const headers = new Headers(options.headers)
    headers.set("Accept", "application/json")

    if (options.body && !(options.body instanceof FormData)) {
      headers.set("Content-Type", "application/json")
    }

    if (includeAuthToken && token) {
      headers.set("Authorization", `Bearer ${token}`)
    }

    return headers
  }

  const accessToken = includeAuthToken ? loadStoredAccessToken() : null
  let response = await fetch(`${API_BASE_URL}${path}`, {
    ...options,
    headers: createHeaders(accessToken),
    cache: "no-store",
  })

  if (response.status === 401 && includeAuthToken) {
    const refreshedToken = await tryRefreshAdminSession()

    if (refreshedToken) {
      updateStoredAccessToken(refreshedToken)
      response = await fetch(`${API_BASE_URL}${path}`, {
        ...options,
        headers: createHeaders(refreshedToken),
        cache: "no-store",
      })
    } else {
      shouldExpireSession = true
    }
  }

  if (response.status === 401 && includeAuthToken) {
    shouldExpireSession = true
  }

  if (shouldExpireSession) {
    clearStoredAdminSession()
    emitAdminSessionExpired()
  }

  if (!response.ok) {
    const details = await response.text()
    throw new Error(details || `Request failed with status ${response.status}`)
  }

  return (await response.json()) as T
}

export function getPlannerOverview(
  date?: string,
  options: RequestInit = {},
): Promise<PlannerOverviewResponseDto> {
  const query = date ? `?date=${encodeURIComponent(date)}` : ""
  console.debug("[planner-api] Fetching planner overview", { date })
  return requestJson<PlannerOverviewResponseDto>(
    `/planner/overview${query}`,
    {
      ...options,
      method: "GET",
    },
    true,
  )
}

export function getWeeklyPlan(
  params?: { date?: string; year?: number; weekNumber?: number },
  options: RequestInit = {},
): Promise<WeeklyPlanResponseDto> {
  const searchParams = new URLSearchParams()
  if (params?.date) searchParams.set("date", params.date)
  if (params?.year) searchParams.set("year", params.year.toString())
  if (params?.weekNumber) searchParams.set("weekNumber", params.weekNumber.toString())
  const queryString = searchParams.toString() ? `?${searchParams.toString()}` : ""

  console.debug("[planner-api] Fetching weekly plan", params)
  return requestJson<WeeklyPlanResponseDto>(
    `/planner/week${queryString}`,
    {
      ...options,
      method: "GET",
    },
    true,
  )
}

export function updateWeeklyGoals(
  planId: string,
  goals: WeeklyGoalItemDto[],
  options: RequestInit = {},
): Promise<WeeklyPlanResponseDto> {
  console.debug("[planner-api] Updating weekly goals", { planId, goals })
  return requestJson<WeeklyPlanResponseDto>(
    `/planner/weeks/${planId}/goals`,
    {
      ...options,
      method: "PUT",
      body: JSON.stringify({ goals }),
    },
    true,
  )
}

export function updateWeeklyPlan(
  planId: string,
  data: { status?: WeeklyPlanStatus; notes?: string },
  options: RequestInit = {},
): Promise<WeeklyPlanResponseDto> {
  console.debug("[planner-api] Updating weekly plan", { planId, data })
  return requestJson<WeeklyPlanResponseDto>(
    `/planner/weeks/${planId}`,
    {
      ...options,
      method: "PATCH",
      body: JSON.stringify(data),
    },
    true,
  )
}

export function createPlannerTask(
  data: CreatePlannerTaskDto,
  options: RequestInit = {},
): Promise<PlannerTaskItemResponseDto> {
  console.debug("[planner-api] Creating task", data)
  return requestJson<PlannerTaskItemResponseDto>(
    "/planner/tasks",
    {
      ...options,
      method: "POST",
      body: JSON.stringify(data),
    },
    true,
  )
}

export function getPlannerTasks(
  params?: {
    date?: string
    startDate?: string
    endDate?: string
    status?: PlannerTaskStatus
    category?: PlannerCategory
  },
  options: RequestInit = {},
): Promise<PlannerTaskItemResponseDto[]> {
  const searchParams = new URLSearchParams()
  if (params?.date) searchParams.set("date", params.date)
  if (params?.startDate) searchParams.set("startDate", params.startDate)
  if (params?.endDate) searchParams.set("endDate", params.endDate)
  if (params?.status) searchParams.set("status", params.status)
  if (params?.category) searchParams.set("category", params.category)
  const queryString = searchParams.toString() ? `?${searchParams.toString()}` : ""

  return requestJson<PlannerTaskItemResponseDto[]>(
    `/planner/tasks${queryString}`,
    {
      ...options,
      method: "GET",
    },
    true,
  )
}

export function updatePlannerTask(
  taskId: string,
  data: UpdatePlannerTaskDto,
  options: RequestInit = {},
): Promise<PlannerTaskItemResponseDto> {
  return requestJson<PlannerTaskItemResponseDto>(
    `/planner/tasks/${taskId}`,
    {
      ...options,
      method: "PATCH",
      body: JSON.stringify(data),
    },
    true,
  )
}

export function deletePlannerTask(
  taskId: string,
  options: RequestInit = {},
): Promise<{ success: boolean; id: string }> {
  return requestJson<{ success: boolean; id: string }>(
    `/planner/tasks/${taskId}`,
    {
      ...options,
      method: "DELETE",
    },
    true,
  )
}

export function togglePlannerTaskCompletion(
  taskId: string,
  data?: TogglePlannerTaskDto,
  options: RequestInit = {},
): Promise<PlannerTaskItemResponseDto> {
  return requestJson<PlannerTaskItemResponseDto>(
    `/planner/tasks/${taskId}/complete`,
    {
      ...options,
      method: "PATCH",
      body: JSON.stringify(data ?? {}),
    },
    true,
  )
}

export interface TodaySummaryResponseDto {
  totalTasks: number
  completedTasks: number
  pendingTasks: number
  completionPercentage: number
  minutesStudied: number
  categoriesStudied: string[]
  streak: number
}

export function getTodaySummary(
  options: RequestInit = {},
): Promise<TodaySummaryResponseDto> {
  console.debug("[planner-api] Fetching today summary")
  return requestJson<TodaySummaryResponseDto>(
    "/planner/summary/today",
    {
      ...options,
      method: "GET",
    },
    true,
  )
}
